### ISSUE TITLE
Eclipse IDE warns of the @SuppressWarnings("PMD") annotations

### ISSUE THREAD

**Issue by yegor256** [yegor256/rexsl#367]
_migrated from Trac, where originally posted by **simtuje** on 13-Apr-2012 7:49am_

The Eclipse IDE flags/warns that it does not understand these annotations:

Unsupported @SuppressWarnings("PMD.UseConcurrentHashMap"),
Unsupported @SuppressWarnings("PMD.AvoidCatchingGenericException"),
Unsupported @SuppressWarnings("PMD.AvoidInstantiatingObjectsInLoops")

Remove that warning,I get a warning that this SuppressWarnings is unsupported, despite the fact that it works.

Open the following two files to see where these annotations are applied:

[http://trac.fazend.com/rexsl/browser/rexsl/trunk/rexsl/rexsl-core/src/main/java/com/rexsl/core/Manifests.java]

[http://trac.fazend.com/rexsl/browser/rexsl/trunk/rexsl/rexsl-core/src/main/java/com/rexsl/core/UserAgent.java]

There may be other java source files in the project with these annotations.

**Comment by slaout** [comment]
This has the disadvantage that Eclipse does not report any unsupported token at all!

There is a bug report on Eclipse project: feel free to support this issue: bugs.eclipse.org/bugs/show_bug.cgi?id=392045

**Comment by mbagat** [comment]
> _migrated from Trac, where originally posted by **yegor256** on 15-Apr-2012 8:13am_
> 
> Thanks, maybe this information will help others.
Thank you yegor256, @SuppressWarnings("PMD")  This piece of line helped me to supress 2 warnings in my jenkin..
