### ISSUE TITLE
get rid of javaassist and work directly with ASM

### ISSUE THREAD

**Issue by yegor256** [yegor256/rexsl#630]
_migrated from Trac, where originally posted by **yegor** on 7-Mar-2013 8:34am_

Let's get rid of javaassist and work directly with ASM, in favor of performance and smaller footprint.

**Comment by yegor256** [comment]
no need to do this any more

**Comment by davvd** [comment]
@yegor256 thanks, paid, **30 mins** to your account, payment ID is `000-21922f43`

+30 added to your rating, current score is: [+5970](http://www.netbout.com/b/35008?open=rating)
