### ISSUE TITLE
Twitter OAuth

### ISSUE THREAD

**Issue by yegor256** [yegor256/rexsl#645]
_migrated from Trac, where originally posted by **yegor** on 17-Mar-2013 7:46am_

Let's add Twitter OAuth to the `AuthInset`

**Comment by davvd** [comment]
@yegor256 it's yours,budget is 30 mins,please go ahead

**Comment by yegor256** [comment]
@davvd assign someone else pls

**Comment by davvd** [comment]
> @davvd assign someone else pls

@yegor256 I will assign somebody else to this issue

**Comment by yegor256** [comment]
the development of this framework is stopped. its successor is here: [takes.org](http://www.takes.org). I'm closing this issue since it won't get any attention any more. thanks all.
