### ISSUE TITLE
RestfulServletTest.java:105-107: This test is disabled because...

### ISSUE THREAD

**Issue by davvd** [yegor256/rexsl#767]
Puzzle `204-f8ee156c` in `rexsl-core/src/test/java/com/rexsl/core/RestfulServletTest.java:105-107` has to be resolved: This test is disabled because of a defect in Jersey: http://java.net/jira/browse/JERSEY-1128. Once it is resolved we can try to enable the test and see how it works.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by yegor256** [comment]
the development of this framework is stopped. its successor is here: [takes.org](http://www.takes.org). I'm closing this issue since it won't get any attention any more. thanks all.
