### ISSUE TITLE
JaxbBundle.java:119-148: A new design would be...

### ISSUE THREAD

**Issue by davvd** [yegor256/rexsl#783]
Puzzle `430-a8950d04` in `rexsl-page/src/main/java/com/rexsl/page/JaxbBundle.java:119-148` has to be resolved: A new design would be required for this class.

The problems

:

 * this.content and this.parent are used as flags, not only as
 * data storage variables.
 * there are three different "types" combined in one class: root
 * element (parent == null), node element (content == null), and
 * leaf element.

The solution

: A new hierarchy of classes:

interface TreeNode abstract AbstractNode implements TreeNode +name: String +attributes: ConcurrentMap abstract SubNode extends AbstractNode +parent: TreeNode InnerNode extends SubNode +children: List LeafNode extends SubNode +content: String DeadNode implements TreeNode // this is the node we set as parent in root node ,>

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by yegor256** [comment]
the development of this framework is stopped. its successor is here: [takes.org](http://www.takes.org). I'm closing this issue since it won't get any attention any more. thanks all.
