### ISSUE TITLE
ErrorRsITCase.java:54-56: Error forwarding doesn't work, for...

### ISSUE THREAD

**Issue by davvd** [yegor256/rexsl#787]
Puzzle `1-b4e0b409` in `src/it/all-correct/src/test/java/com/rexsl/foo/ErrorRsITCase.java:54-56` has to be resolved: Error forwarding doesn't work, for some strange reason. It worked fine in version 1.0, but started to fail in version 1.1.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by yegor256** [comment]
the development of this framework is stopped. its successor is here: [takes.org](http://www.takes.org). I'm closing this issue since it won't get any attention any more. thanks all.
