### ISSUE TITLE
Rexsl doc contains wrong link on jar

### ISSUE THREAD

**Issue by longtimeago** [yegor256/rexsl#802]
This page http://www.rexsl.com/page-builder.html contains link on ```rexsl-page-1.3.1.jar``` (http://repo1.maven.org/maven2/com/rexsl/rexsl-page/1.3.1/rexsl-page-1.3.1.jar)
Looks like it's broken, as there is no artifact with such version in maven repository.

**Comment by yegor256** [comment]
the development of this framework is stopped. its successor is here: [takes.org](http://www.takes.org). I'm closing this issue since it won't get any attention any more. thanks all.
